server:
  port: ${TOMCAT_PORT:8081}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/compasschallenge3_msaddress?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  mvc:
    format:
      date-time: iso

springdoc:
  swagger-ui:
    path: /docs-msaddress.html
  api-docs:
    path: /docs-msaddress
  packages-to-scan: com.compassuol.sp.challenge.msaddress.web.controller